name: pt and pt accessories
description: >
    Paul S. Tang
about: >
    Big fan of nonparametric samplers.

master_repo: true
url: "https://ptsw.ca"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

#paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           "Paul Tang"
  #avatar:         "https://avatars2.githubusercontent.com/u/1909634?s=460&v=4"
  #email:          "ptsw1990 -at- gmail -dot- com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: _ptsw
  github: https://github.com/paultsw
  stackexchange: https://stackoverflow.com/users/3141064/ptsw
  #linkedin: (N/A)
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:

# Analytics and webmaster tools stuff goes here
#google_analytics:
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:
